external_data_config:
  external_data_csv: ./data/external/Churn_Prediction.csv
mlflow_config:
  artifacts_dir: /home/k8user/Akhil/mlops/mlflow/mlruns
  experiment_name: Churn_mlops
  registered_model_name: random_forest_model
  remote_server_uri: http://172.27.35.85:5000/
  run_name: random_forest
model_dir: ./models/model.joblib
model_monitor:
  drift_score: 0.018684447131985818
  monitor_dashboard_html: ./reports/templates/data_and_target_drift_dashboard.html
  monitor_dashboard_json: ./reports/templates/data_and_target_drift_dashboard.json
  target_col_name: target
model_webapp_dir: webapp/model_webapp_dir/model.joblib
processed_data_config:
  processed_data_csv: ./data/processed/processed_data.csv
  test_data_csv: ./data/processed/churn_test.csv
  train_data_csv: ./data/processed/churn_train.csv
random_forest:
  max_depth: 31
  n_estimators: 9
raw_data_config:
  model_var:
  - CreditScore
  - Geography
  - Gender
  - Age
  - Tenure
  - Balance
  - NumOfProducts
  - HasCrCard
  - IsActiveMember
  - EstimatedSalary
  - Exited
  new_train_data_csv: ./data/raw/train_new.csv
  random_state: 111
  raw_data_csv: ./data/raw/Churn_Prediction.csv
  target: Exited
  train_test_split_ratio: 0.2
