apiVersion: v1
kind: Service
metadata:
  name: mlflow-churn
  labels:
    app: mlflow-churn
  namespace: mlops
spec:
  type: NodePort
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app: mlflow-churn
